name: Update Sponsors in README

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Update Sponsors in README
        uses: JamesIves/github-sponsors-readme-action@v2.0.1
        with:
          token: ${{ secrets.PAT }}
          template-path: README.md
